//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP03Yaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablitsaZayavki
    {
        public int PP { get; set; }
        public string LastNameS { get; set; }
        public string FirstNameS { get; set; }
        public string MiddleNameS { get; set; }
        public string LastNameO { get; set; }
        public string FirstNameO { get; set; }
        public string MiddleName { get; set; }
        public string DescriptionOfTheProblem { get; set; }
        public Nullable<int> OfficeNumber { get; set; }
        public string EmployeeTelephoneNumber { get; set; }
    }
}
