//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP03Yaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablitsaRoli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TablitsaRoli()
        {
            this.TablitsaPolzovateleys = new HashSet<TablitsaPolzovateley>();
        }
    
        public int PPRole { get; set; }
        public string RoleTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TablitsaPolzovateley> TablitsaPolzovateleys { get; set; }
    }
}
