//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP03Yaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablitsaPolzovateley
    {
        public int PPUser { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IdRole { get; set; }
    
        public virtual TablitsaRoli TablitsaRoli { get; set; }
    }
}
